### ISSUE TITLE
running `turbo dev` fails

### ISSUE THREAD

**Issue by jmikedupont2** [jsonresume/jsonresume.org#146]
running `pnpm turbo dev` 

```
Need to install the following packages:
jsonresume-theme-full:dev: livereloadx@0.3.10
@jsonresume/theme-stackoverflow:dev: info => Modifying Create React App rules.
@jsonresume/theme-stackoverflow:dev: info => Using default Webpack5 setup
@jsonresume/theme-stackoverflow:dev: <i> [webpack-dev-middleware] wait until bundle finished
@jsonresume/theme-stackoverflow:dev: 10% building ...ack-dev-server@4.15.1_webpack@5.89.0/node_modules/@pmmmwh/react-re@jsonresume/theme-stackoverflow:dev: 24% building ...ules/.pnpm/babel-loader@8.3.0_@babel+core@7.24.7_webpack@5.89.0/no@jsonresume/theme-stackoverflow:dev: 24% building ..../node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.89.0/node_m@jsonresume/theme-stackoverflow:dev: 31% building ...oader ../../node_modules/.pnpm/style-loader@3.3.3_webpack@5.89.0/n@jsonresume/theme-stackoverflow:dev: 31% building ...rt loader ../../node_modules/.pnpm/css-loader@6.8.1_webpack@5.89.0@jsonresume/theme-stackoverflow:dev: 31% building ...dules/.pnpm/postcss-loader@6.2.1_postcss@8.4.39_webpack@5.89.0/nod@jsonresume/theme-stackoverflow:dev: 29% building import loader ../../node_modules/.pnpm/unplugin@0.10.2/node_modules/u@jsonresume/theme-stackoverflow:dev: 77% sealing module and chunk tree optimization PersistentChildCompilerSingletonPlu@jsonresume/theme-stackoverflow:dev: 

ERROR in [eslint] Plugin "react" was conflicted between ".eslintrc.cjs » @repo/eslint-config-custom » eslint-config-next" and "BaseConfig » /mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/eslint-config-react-app@7.0.1_@babel+plugin-syntax-flow@7.24.7_@babel+plugin-transform-react-_2crgda7qjvads5wzs3lbc6kfeq/node_modules/eslint-config-react-app/base.js".
@jsonresume/theme-stackoverflow:dev:

@jsonresume/theme-stackoverflow:dev: preview compiled with 1 error

@jsonresume/theme-stackoverflow:dev: <i> [webpack-dev-middleware] wait until bundle finished
@jsonresume/theme-stackoverflow:dev: 10% building ...ack-dev-server@4.15.1_webpack@5.89.0/node_modules/@pmmmwh/react-re@jsonresume/theme-stackoverflow:dev: 24% building ...ules/.pnpm/babel-loader@8.3.0_@babel+core@7.24.7_webpack@5.89.0/no@jsonresume/theme-stackoverflow:dev: 24% building ..../node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.89.0/node_m@jsonresume/theme-stackoverflow:dev: 31% building ...oader ../../node_modules/.pnpm/style-loader@3.3.3_webpack@5.89.0/n@jsonresume/theme-stackoverflow:dev: 31% building ...rt loader ../../node_modules/.pnpm/css-loader@6.8.1_webpack@5.89.0@jsonresume/theme-stackoverflow:dev: 31% building ...dules/.pnpm/postcss-loader@6.2.1_postcss@8.4.39_webpack@5.89.0/nod@jsonresume/theme-stackoverflow:dev: 29% building import loader ../../node_modules/.pnpm/unplugin@0.10.2/node_modules/u@jsonresume/theme-stackoverflow:dev: 77% sealing module and chunk tree optimization PersistentChildCompilerSingletonPlu@jsonresume/theme-stackoverflow:dev: ERROR in [eslint] Plugin "react" was conflicted between ".eslintrc.cjs » @repo/eslint-config-custom » eslint-config-next" and "BaseConfig » /mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/eslint-config-react-app@7.0.1_@babel+plugin-syntax-flow@7.24.7_@babel+plugin-transform-react-_2crgda7qjvads5wzs3lbc6kfeq/node_modules/eslint-config-react-app/base.js".
@jsonresume/theme-stackoverflow:dev:
@jsonresume/theme-stackoverflow:dev: preview compiled with 1 error
@jsonresume/theme-stackoverflow:dev: WARN Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
@jsonresume/theme-stackoverflow:dev: WARN Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
@jsonresume/theme-stackoverflow:dev: 99% end closing watch compilationWARN Force closed preview build
@jsonresume/theme-stackoverflow:dev: ERR! SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
@jsonresume/theme-stackoverflow:dev: ERR! Run Storybook with --debug-webpack for more information.
@jsonresume/theme-stackoverflow:dev: ERR!     at starter (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+builder-webpack5@7.5.3_esbuild@0.23.0_typescript@4.9.5/node_modules/@storybook/builder-webpack5/dist/index.js:1:6698)
at starter.next (<anonymous>)
@jsonresume/theme-stackoverflow:dev: ERR!     at Module.start (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+builder-webpack5@7.5.3_esbuild@0.23.0_typescript@4.9.5/node_modules/@storybook/builder-webpack5/dist/index.js:1:8727)
@jsonresume/theme-stackoverflow:dev: ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
@jsonresume/theme-stackoverflow:dev: ERR!     at async storybookDevServer (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+core-server@7.0.7/node_modules/@storybook/core-server/dist/index.js:35:7062)
@jsonresume/theme-stackoverflow:dev: ERR!     at async buildDevStandalone (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+core-server@7.0.7/node_modules/@storybook/core-server/dist/index.js:48:2786)
@jsonresume/theme-stackoverflow:dev: ERR!     at async withTelemetry (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+core-server@7.0.7/node_modules/@storybook/core-server/dist/index.js:35:3422)
@jsonresume/theme-stackoverflow:dev: ERR!     at async dev (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+cli@7.0.7/node_modules/@storybook/cli/dist/generate.js:434:400)
@jsonresume/theme-stackoverflow:dev: ERR!     at async Command.<anonymous> (/mnt/data1/nix/time/2024/09/11/json-crypto-wallet.org/node_modules/.pnpm/@storybook+cli@7.0.7/node_modules/@storybook/cli/dist/generate.js:436:225) {
@jsonresume/theme-stackoverflow:dev: ERR!   data: { errors: [ [Object] ] },
@jsonresume/theme-stackoverflow:dev: ERR!   documentation: false,
@jsonresume/theme-stackoverflow:dev: ERR!   fromStorybook: true,

```

**Comment by levino** [comment]
I am not sure that `turbo dev` is supported. What did you want to do? Do the changes in #145 fix this particular issue? If so, there might still be other issues with the command. I think it is better to run only the dev script of the package you want to change.

**Comment by jmikedupont2** [comment]
I am just following the readme, I worked around this by removing the custom eslint totally.  https://github.com/jsonresume/jsonresume.org/pull/147 here are my changes, this bug went away. 
This is my first time ever working with eslint and storybrook so please excuse my totall ignorance of all standards.

**Comment by levino** [comment]
I can reproduce the issue. I think we only have a dev script in four packages atm:
- `registry`
- `homepage2`
- `@jsonresume/stack-overflow`
- `jsonresume-theme-full`

It seems to me the `registry` and `homepage2` do run fine.

`jsonresume-theme-full` has a problematic dev script which should be removed:
https://github.com/jsonresume/jsonresume.org/blob/40b46fe4492f3d7baebb1fc8609864e4c2311cfb/packages/jsonresume-theme-full/package.json#L24
It tries to use `npx` to install `livereloadx` on the fly and run it. This is a no no for me. `livereloadx` should be a development dependency of `jsonresume-theme-full`. Since user confirmation is needed to allow the installation of `livereloadx`, the script hangs when run via `turbo`. Even it if were to fail, I am not sure if it be useful for the overall stack. I let the script install `livereloadx` locally and then the script succeeds but does not provide anything useful on the web server. The readme also references non existent files live `dev/index.html` etc. I think a lot of stuff has changed in the package and the people doing the changes forgot to update the Readme and the scripts. Also the migration to this monorepo here has been done rather sloppily, probably because of time constraints. I would for now just remove all the scripts from the package.

Now the `dev` script of `@jsonresume/theme-stackoverflow` (which is maintained by myself) starts a storybook server for the react components used in the theme. This is also irrelevant for the overall stack, as long as the `build` script works, which it does.

## To dos

So what should we do now? I recommend the following and would like a confirmation from @thomasdavis:

- [ ] Remove the support and mentioning of `turbo dev` on a global level. I think it makes little sense for this to be supported. Lets imagine we have 20 themes which all have a storybook which starts when running the `dev` script. They would all try to run on port 6006. What is more important is to make `build` a dependency for `dev`. So if one would run `turbo dev` in package A and packages B and C are dependencies of package A, then `turbo` would first (try to) build packages B and C before starting the `dev` script in package A. Maybe we could add a `dev` script in the root `package.json` which does something like `echo "Please run the dev scripts individually" && exit 1;`.
- [ ] Remove the scripts and the Readme in `jsonresume-theme-full` since it is all outdated and makes little sense (the Readme even talks of installing node 15 and using `npm` etc.)
- [ ] Fix the dev script in `@jsonresume/theme-stackoverflow`. _fwiw: I will just do that without waiting for confirmation._

**Comment by levino** [comment]
So for me and as I hoped, #145 fixes the broken `dev` script of `@jsonresume/theme-stackoverflow`.

**Comment by jmikedupont2** [comment]
https://github.com/meta-introspector/json-crypto-wallet.org/actions/runs/10832551866 I have gotten my version to finally lint and build by removing more eslint stuff.

**Comment by levino** [comment]
I am sorry, I do not see how this is related.

**Comment by jmikedupont2** [comment]
This is related because it's a fork of the code I try to get it run I had to make some changes to get it to run I was trying to get the GitHub actions to run and I encountered all types of difficulties and I documented some of those so this is the general Improvement and some things that have to be fixed for this project but I did spend some time on it and as a new user it was hard to get this thing to deploy or run in the GitHub actions

**Comment by levino** [comment]
Ah, okay. `json-crypto-wallet` is a surprising name for a fork. Please create issues and PRs to this repo here to get support. I cannot provide support for forks.

Once you have made a PR, I am happy to discuss improvements. However in your past PRs I saw a certain mixture of concerns (adding new buttons and fixing ci scripts in the same PR). It will be easier if you make multiple PRs, one for each topic. Also please create issues before creating PRs so we can discuss the tasks first before looking at the solutions.

**Comment by jmikedupont2** [comment]
my plan is to add a set of crypto wallet to mix so that the users can accept and send payments and host them in github secrets. 
We can close this issue because i resolved the open issues.

**Comment by thomasdavis** [comment]
I have been on a holiday, let me digest this and get back to it.

**Comment by levino** [comment]
Good morning @thomasdavis,
I hope you had a good start after the vacation. Please have a look and let's work on closing this, if you can.

**Comment by thomasdavis** [comment]
## ✅ Issue Resolved

Tested `pnpm turbo dev` and it's working correctly now.

### Root Cause
The ESLint plugin conflict was caused by Storybook v7.0.7 (mentioned in your error logs from Sept 2024).

### Current Status
- **Storybook version**: v8.6.14 (upgraded from v7.0.7)
- **ESLint conflicts**: ✅ Resolved
- **Dev server**: ✅ Starting successfully

### Test Results
```bash
$ pnpm turbo dev
✓ homepage2 ready on http://localhost:3002
✓ registry ready on http://localhost:3000  
✓ @jsonresume/theme-stackoverflow Storybook starting on port 6006
```

All packages compile without ESLint errors. The dependency upgrades resolved the conflicting ESLint configurations.

Closing as resolved.
